version: '3.7'
services:
  phoenix:
    build: .
    ports: 
      - 4000:4000
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: clan_calendar_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: psql
    depends_on:
      - psql
    volumes:
    - .:/usr/src/app
  psql:
    image: postgres:alpine
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clan_calendar_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: